### ISSUE TITLE
Zoom buttons should be visible at the right lower corner

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-activity-poi#19]
... if possible also add the 'my-location' button

**Comment by Piiit** [comment]
Cannot see them

**Comment by davidebz** [comment]
The bundle.js on the testing page is not the same as

https://github.com/noi-techpark/webcomp-activity-poi/blob/development/dist/bundle.js

Search for example for 

let map = L.map(mapdiv, { zoomControl: false })

the testing server hasn't the zoomControl: false

**Comment by Piiit** [comment]
@davidebz You are right, sorry forgot to merge into master branch first... my fault....

Sorry for the extra work

**Comment by davidebz** [comment]
no problem :-)
