### ISSUE TITLE
Categories should be English

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-activity-poi#20]
@RudiThoeni is that possible? (not so important, only if already implemented)

@davidebz What was the API call you queried?

**Comment by RudiThoeni** [comment]
http://tourism.opendatahub.bz.it/api/ODHActivityPoiTypes
they are in all languages?

the id is in german for historical reasons i cannot change this so easily.........

**Comment by Piiit** [comment]
@RudiThoeni OK, that is what we wanted to know... so since this is low-priority, I will close it... (benefit is too small for all the effort)

**Comment by RudiThoeni** [comment]
ok i wanted to change this since long long time...... but there is so a "rattenschwanz" hanging on this.... i have to inform all web companies that are using this etc.. etc....  but maybe this year is the right to change this ;)

**Comment by RudiThoeni** [comment]
I found something that can be used

the object
AdditionalPoiInfos

contains MainType, SubType, PoiType in every language

**Comment by RudiThoeni** [comment]
but let's wait maybe i add this info to the "PoiProperty" Object.....  will write how to proceed

**Comment by RudiThoeni** [comment]
Hi together

I made a new field in
AdditionalPoiInfos[language].Categories

It is a list, and we can configure what categories are shown.... At the moment Categories not interesting for the users like "Summer" etc... are not shown in the list..... it can also occur that the list is empty

The idea was to show this categories of the list, forget about this Type, PoiType, SubType etc....  

also for the other webcomponents @Piiit i think this is the best way to display the categories

**Comment by RudiThoeni** [comment]
![image](https://user-images.githubusercontent.com/30471361/110953889-25344a80-8348-11eb-85eb-757e81d8079e.png)

**Comment by Piiit** [comment]
@RudiThoeni Do you have time to add that in the code? I think @davidebz is at the moment longer working on this web component.... the iteration is over.

**Comment by RudiThoeni** [comment]
this is implemented with the new "Tags"
